name: Z4PDFScan
options:
  bundleIdPrefix: com.zhou0810
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"

targets:
  Z4PDFScan:
    type: application
    platform: iOS
    sources:
      - Z4PDFScan
    settings:
      base:
        INFOPLIST_FILE: Z4PDFScan/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        PRODUCT_BUNDLE_IDENTIFIER: com.zhou0810.Z4PDFScan
        GENERATE_INFOPLIST_FILE: false
