name: MacIntelVirtMgr
options:
  bundleIdPrefix: com.shaopingzhou
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "16.2"

settings:
  base:
    DEVELOPMENT_TEAM: Y84Z25C7RJ
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  MacIntelVirtMgr:
    type: application
    platform: macOS
    sources:
      - MacIntelVirtMgr
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shaopingzhou.MacIntelVirtMgr
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        INFOPLIST_KEY_CFBundleDisplayName: MacIntelVirtMgr
        CODE_SIGN_ENTITLEMENTS: MacIntelVirtMgr/MacIntelVirtMgr.entitlements
        ENABLE_APP_SANDBOX: NO
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - sdk: Virtualization.framework
